### ISSUE TITLE
Current suggestions from @bigwad

### ISSUE THREAD

**Issue by dan31** [StarcounterPrefabs/LogStreamer#10]
Extracting it from other discussion. @linkdata what's your view on these?

1. Seeding of new replica. Now we require master to have all log files in place from the start of database life. I don’t think it’s practical.
2. Tool to tell safely remove (or backup) unused logs and optimized log files. It relates to replication in that sense we can’t safely remove log file if we have replication partner that requires data from it.
3. Get rid of polling of new available log record. Now replicator polls disk log every 100ms to find out new log records. We may want to optimize it.

For No.2, you probably recall the demand, that we need to somehow provide a way for Starcounter users to be aware of what log files are still needed and cannot be removed. The tool which can clean up the log files not needed by the replicator needs to be replicator-aware and thus a part of a replicator bundle. The tool instead might just provide a listing of the files currently needed for replicator, thus the output of the tool is an input to any other batch processing. In installer we might create an option to setup a Windows task or PowerShell routine to clean-up log files on a regular basis.

**Comment by dan31** [comment]
Related to https://github.com/Starcounter/Starcounter/issues/2882

**Comment by linkdata** [comment]
1.

Log "compression" (multiple updates -> one etc) can be probably done safely without knowledge of replication states, as it's deterministic. Probably, because commit triggers might introduce side effects on the receiver (if they trigger for log applicator operations?)

2.

Just removing logs (as opposed to "compressing" them) is unsafe.

The local database replicator doesn't know what's "safe" to remove since the definition of that changes with the replication tree structure and the state of replication peers. At best it could make weak guesses, but those would break as soon as a new replication child connects or the replication state on any of the peers change unexpectedly.

In addition, since we allow users to define the set of tables to be replicated, and this set can change over time, if you remove logs the consequence is that you won't be able to add new, previously not replicated, tables to the set.

I believe these limitations can be worked around using log compression.

3.

Polling is bad, but I'll let @bigwad worry about the log reader implementation performance.

**Comment by linkdata** [comment]
This is now tracked in https://github.com/Starcounter/CompanyTrack/issues/177, so closing this.
