### ISSUE TITLE
Move Replicator to prefab / samples?

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/LogStreamer#5]
It will better illustrate that we consider it a sample / something to build from, that if it's under Starcounter.

**Comment by linkdata** [comment]
I will move this to StarcounterSamples once I get the all-clear from @per-samuelsson.

I would also like to rename it to `DataStreamer` which better reflects what it actually does. The terms "replicator" and "replication" usually mean something else than what this project does. While the DataStreamer could be used to maintain a fairly up-to-date copy of a master database, it is not the main use-case.

I'm not set on the new name, I mainly just don't want it to be called "Replicator" since replication is implied to mean [consistency among the databases being replicated](https://en.wikipedia.org/wiki/Replication_(computing)), which we don't do since we don't do distributed transactions or distributed locking.

**Comment by warpech** [comment]
If this app has a feature that is considered production ready (and is used in production anywhere) then this should be a prefab. Otherwise a sample. 

@per-samuelsson, @linkdata please give me a final opinion on this and I will update the list at https://github.com/Starcounter/CompanyTrack/issues/142 and move this repo accordingly.

**Comment by linkdata** [comment]
I'm fine with it being moved to prefabs. Just be sure you let both me and @per-samuelsson know before you do it so we can check in anything pending.

**Comment by per-samuelsson** [comment]
@linkdata 

Go ahead and move it, and rename it as you see fit. You know better than me what to name it. I'm fine with what you settle with. I agree that Replicator is misleading, so I think any other name is better really. DataStreamer is fine. LogDistributor, LogSender, LogStreamer are other options. Or something with Sync or Copy. You choose. :smile: 

@linkdata @warpech 

I'm not 100% sure where this one should be. I think both samples and prefabs are warranted. I'll let you guys take the decision.

**Comment by linkdata** [comment]
Bikeshedding a bit I guess, but I like your suggesting of having `Log` in the name. It is after all very logcentric. I think I'll go with `LogStreamer`.

**Comment by linkdata** [comment]
I'm going to try to move this to Prefabs now. If I run into problems, I'll yell for @warpech to come rescue me.

**Comment by linkdata** [comment]
Moved and renamed, so closing. Expect a bunch of rename commits to follow.
